### ISSUE TITLE
Only run POST_SCRIPT on *successful* backup.

### ISSUE THREAD

**Issue by CorneliousJD** [tiredofit/docker-db-backup#123]
**Description of the feature**
Another variable of "POST_SCRIPT_SUCCESS" that defaults to false (same operation is it is now) but if set to true will only execute the post script on successful backup.

**Benftits of feature**
I am using my POST_SCRIPT to send a curl request to health-checks.io so I can easily monitor and alert if backup jobs are missed for too long in a row, but right now even with backups failing due to #122, the script is continuing to run thus making it seem like backups are working, when they aren't. 

**Additional context**
Having this optional feature set and default to false will retain all existing configurations the way they are, but allow users to set the variable to TRUE in order to avoid the type of false positive monitoring I am seeing on my side with my specific setup.

Thank you for considering this request.

**Comment by tiredofit** [comment]
HI there, Since we send status of if a backup completed or didn't complete to the [custom scripts](https://github.com/tiredofit/docker-db-backup#custom-scripts). I'm going to implement this. You could easily do this in the script to only fire on success like so:

````bash

#!/bin/bash

if [ "$1" = "0" ] ; then
   <your script that fires>
fi
````
Anything other than `0` is a failure in some capacity... 
I hope this helps...]
