### ISSUE TITLE
[3.8.4] cron dont persist system reboots on unraid

### ISSUE THREAD

**Issue by MisterT87** [tiredofit/docker-db-backup#214]
First of all: Thank you for your work :)

I am using Unraid 6.11.5 and using db-backup 3.8.4.

I looked into logs and realized cron wont persist system reboots. 
I have setup DB_DUMP_FREQ to 10080 (7 days).

### Steps to reproduce

Watched image logs:
before system reboot:
2023-04-07.22:20:01 [NOTICE] ** [db-backup] Sleeping for another 604799 seconds. Waking up at 2023-04-14 22:20:00 CEST 

after reboot:
2023-04-08.12:53:01 [INFO] ** [db-backup] Next Backup at 2023-04-08 22:20:00 CEST

### What is the expected *correct* behavior?

Do the next backup on 2023-04-14 22:20:00 CEST 

### Environment
- Image version / tag:  3.8.4
- Host OS: Unraid 6.11.5

Unraid is no normal linux distro...
Its rebuild from scratch and running from a USB drive 
(no system files changes will persist after reboot, outside personal mounts - e.g. /etc )
    
### Possible fixes
Maybe add a new environment variable that points to a configuration folder on the host OS.
In this configuration folder: Maybe add a file with "Next Backup date and time" content. Which cron will check on every image start.

**Comment by tiredofit** [comment]
Hi - thanks, you are right - this container resets its timings post reboot due to the way I wrote the timers which don't keep state information. In fact a lot of my containers don't do too well upon reboot due to the S6 Overlay and the sometimes complex initialization routines.

I'll note this state suggestion and leave this issue open as a potential feature.

**Comment by MisterT87** [comment]
@tiredofit thanks :)
this means I only can make daily db backups or dont reboot ?

**Comment by tiredofit** [comment]
A bit of both actually :) 
 
My servers generally run for months at a time before a reboot but I understand that's not entirely common. I also backup once, or more times in a day, sometimes every 10 minutes for some services. Again, everyone has different use cases...

I'd set your `DB_BACKUP_BEGIN` perhaps to something like `+10` so that it backs up 10 minutes after you restart and then work with the `DB_DUMP_FREQ` option to tune what you are looking to do. You may get more backups than usual however more is better than less IMO.

I use this timer code all over my images and in another backup image ([tiredofit/restic](https://github.com/tiredofit/docker-restic)). I'll see if I can find some sponsors to implement this across all the images that have this timer code.

**Comment by MisterT87** [comment]
@tiredofit thanks for explanation :)

Your workaround with DB_BACKUP_BEGIN wont work for me.
Generally I will 100% agree - but this is a Home Server and most of the times it will shutdown daily to reduce huge electricity cost :(

**Comment by benvia** [comment]
I've just push a pull request with a proposal. I'm not sure that's the best solution but it can do the job.

**Comment by tiredofit** [comment]
Version 4.0.0 https://github.com/tiredofit/docker-db-backup/releases/tag/4.0.0 contains 2 new scheduling options - one of them courtesy of @benvia which takes a full date stamp to start backing up. Hopefully this solves your backup starting woes.
