### ISSUE TITLE
Backup compression

### ISSUE THREAD

**Issue by tadeo-n** [tiredofit/docker-db-backup#36]
The backup and compression process seems not to be optimal.

We have the following problem:

- Original MongoDB database size is +9 GB
- +50 GB .bson files are created
- A .tar +50 GB is created
- A Gzip / Bzip / Xzip +15 GB file is generated 
- Once completed, de process delete temporary files

In our case, files take up  more than 115 GB (50 + 50 + 15 GB) are created temporarily.

Is there a way to optimize this? For example:
- Skip the intermediate step of generating the .tar file (directly generating .tar.gz)
- Directly generating the compressed backup `mongodump --gzip` or `mongodump | gzip`

**Comment by tiredofit** [comment]
I can see where this is happening due to the functions involved with compression being performed after the backup. Yes this deserves some optimizations. I will think about how to accomplish this and put something together in coming weeks.

**Comment by tiredofit** [comment]
Just did some cursory investigations on this.
I'm having problems getting a pipe command to work properly, doesn't look like it's well supported.
Only collections are supported to send to stdout/pipe.

`mongodump --gzip --archive=/path` does seem to work but only for gzip no other compression options (type, compression size) are available. I tried to set `--archive-path=-` to attempt to pipe but no luck. If you (or other users of image!) have any pointers or any successes with being able to get piping to work I can integrate this in, otherwise I'll sit and think about this more for a while to see how to further optimize this. Regardless I can cut down some of the files by merging a few of the functions together.

**Comment by tiredofit** [comment]
The weeks go by so quickly it seems! See version `2.0.0` . This eliminates the temp files, changes the way that compression is performed although Mongo only will support GZ compression. The suffix of the backup for MongoDB is now `.archive` and if compressed will be `.archivegz` - Images are already on Docker Hub..

**Comment by tadeo-n** [comment]
Tomorrow (i think) i'll be able to try it.
Thank you!

**Comment by tadeo-n** [comment]
I confirm that this solution works! Now backup takes 20min and 2.7GB of space.

Backup can be restored using:
`mongorestore --host="<server>" --port=<port> --gzip --archive=/backup/file.archivegz`

Good Job!

**Comment by tiredofit** [comment]
Right on! Glad it's worked out.
