### ISSUE TITLE
Is it support for multiple DB backups at the same time?

### ISSUE THREAD

**Issue by VagrantPi** [tiredofit/docker-db-backup#8]
Can your DB_TYPE support multiple DBs at the same time?
In my case, I want to back up mongo, redis at the same time.

**Comment by tiredofit** [comment]
At this time no, just because of the seperat hosts/user/pass combos. If you find a clean way to do it feel free to submit a PR and I will merge in.

I too run container stacks with multiple DB Engines. I simply just run multiple containers with container_names that are descriptive: `servicename-domain-tld-db-backup-redis`. and so on.

**Comment by VagrantPi** [comment]
thanks your're response
