### ISSUE TITLE
Unable to upload to minio

### ISSUE THREAD

**Issue by mogupta** [tiredofit/docker-db-backup#87]
https://github.com/tiredofit/docker-db-backup/blob/f276af251216c881de10b70a3ef204193a721020/install/etc/services.available/10-db-backup/run#L424

In the below example, endpoint-url is provided, but missing above
`aws --endpoint-url https://play.min.io:9000 s3 cp simplejson-3.3.0.tar.gz s3://mybucket`

**Comment by jacksgt** [comment]
Hello,

it appears that since release 2.11.0 (in particular https://github.com/tiredofit/docker-db-backup/commit/4d6419fd184590c3620a7a9a5e70ef3adecb97ee ) this variable is actually functional again!
I got it working with this config for Backblaze, so you can give Minio a try again:
```sh
BACKUP_LOCATION=S3
BACKUP_TYPE=S3 # note: both variables currently need to be set!
S3_BUCKET=my-bucket
S3_HOST=s3.us-west-001.backblazeb2.com
S3_KEY_ID=foo
S3_KEY_SECRET=bar
S3_PATH=backup
S3_REGION=us-west-001
S3_URI_STYLE=Path # note: this needs to be set, but doesn't do anything
```
which generates the correct command:
```
aws --endpoint-url https://s3.us-west-001.backblazeb2.com s3 cp /tmp/backups/mysql_test_mariadb_20220205-231128.sql.bz2 s3://my-bucket/backup/mysql_test_mariadb_20220205-231128.sql.bz2
```

Good luck!
